let recipe = [
    
    {
      id: 2,
      foodImage: "imgs/garlic-butter-salmon-3.jpg",
      foodName: "Chicken",
      foodtype: "African meat,Garlic Salmon",
      rating: 3.4,
      time: 15,
      pbg: " rgba(145, 126, 1, 0.256)",
      sbg: " rgba(91, 173, 10, 0.256)",

      recipeVideo:"",
      recipeDesc:"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odio sunt sequi natus? Minus eos, eius odit optio autem nam totam amet quas quasi, sapiente aliquid accusantium, quo earum dolore distinctio!",
      downloadRecipe:"",
      i1:"consectetur",
      i2:"consectetur",
      i3:"consectetur",
      i4:"consectetur",
      i5:"consectetur",
      src:""
    },
    {
      id: 3,
      foodImage: "imgs/tomato-soup-recipe.jpg",
      foodName: "Pankage",
      foodtype: "Asian Fish Soup,Tomato Soup",
      rating: 2.5,
      time: 45,
      pbg: " rgba(139, 6, 137, 0.256)",
      sbg: " rgba(139, 6, 137, 0.256)",
      recipeVideo:"",
      recipeDesc:"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odio sunt sequi natus? Minus eos, eius odit optio autem nam totam amet quas quasi, sapiente aliquid accusantium, quo earum dolore distinctio!",
      downloadRecipe:"",
      i1:"consectetur",
      i2:"consectetur",
      i3:"consectetur",
      i4:"consectetur",
      i5:"consectetur",
      src:""
    },
    {
      id: 4,
      foodImage: "imgs/bakedchickenbreast.jpg",
      foodName: "Baked chicken Breast",
      foodtype: "American chicken,Baked chicken Breast",
      rating: 3.5,
      time: 34,
      pbg: " rgba(213, 12, 29, 0.256)",
      sbg: " rgba(213, 12, 29, 0.256)",
      recipeVideo:"",
      recipeDesc:"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odio sunt sequi natus? Minus eos, eius odit optio autem nam totam amet quas quasi, sapiente aliquid accusantium, quo earum dolore distinctio!",
      downloadRecipe:"",
      i1:"consectetur",
      i2:"consectetur",
      i3:"consectetur",
      i4:"consectetur",
      i5:"consectetur",
      src:""
    },
    {
      id: 1,
      foodImage: "imgs/Caesar-Salad.jpg",
      foodName: "Ceaser Salad",
      foodtype: "American Fish ,Ceaser Salad",
      rating: 4.5,
      time: 34,
      pbg: " rgba(255, 136, 0, 0.256)",
      sbg: " rgba(255, 136, 0, 0.256)",
      recipeVideo:"",
      recipeDesc:"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odio sunt sequi natus? Minus eos, eius odit optio autem nam totam amet quas quasi, sapiente aliquid accusantium, quo earum dolore distinctio!",
      downloadRecipe:"",
      i1:"consectetur",
      i2:"consectetur",
      i3:"consectetur",
      i4:"consectetur",
      i5:"consectetur",
      src:"imgs/Snowfall_-_S02E05_-_Serpiente_5b6614571f66e7f79e26a04124f3964f.webm"

    },
    {
      id: 8,
      foodImage: "imgs/banku-and-tilapia-2.jpg",
      foodName: "Banku and tilapia",
      foodtype: "African Fish pepper,Banku and tilapia",
      rating: 2.5,
      time: 45,
      pbg: " rgba(139, 6, 137, 0.256)",
      sbg: " rgba(139, 6, 137, 0.256)",
      recipeVideo:"",
      recipeDesc:"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odio sunt sequi natus? Minus eos, eius odit optio autem nam totam amet quas quasi, sapiente aliquid accusantium, quo earum dolore distinctio!",
      downloadRecipe:"",
      i1:"consectetur",
      i2:"consectetur",
      i3:"consectetur",
      i4:"consectetur",
      i5:"consectetur",
      src:"imgs/Snowfall_-_S02E05_-_Serpiente_5b6614571f66e7f79e26a04124f3964f.webm"
      
    },
    {
      id: 6,
      foodImage: "imgs/tacco.jpg",
      foodName: "Taco",
      foodtype: "Mexico, Taco",
      rating: 1.5,
      time: 30,
      pbg: " rgba(255, 136, 0, 0.256)",
      sbg: " rgba(255, 136, 0, 0.256)",
      recipeVideo:"",
      recipeDesc:"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odio sunt sequi natus? Minus eos, eius odit optio autem nam totam amet quas quasi, sapiente aliquid accusantium, quo earum dolore distinctio!",
      downloadRecipe:"",
      i1:"consectetur",
      i2:"consectetur",
      i3:"consectetur",
      i4:"consectetur",
      i5:"consectetur",
      src:""
    },
    {
      id: 7,
      foodImage: "imgs/spag.jpg",
      foodName: "spaggetti chicken",
      foodtype: "Asian Chicken,spaggetti chicken",
      rating: 2.5,
      time: 20,
      pbg: " rgba(213, 12, 29, 0.256)",
      sbg: " rgba(213, 12, 29, 0.256)",
      recipeVideo:"",
      recipeDesc:"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odio sunt sequi natus? Minus eos, eius odit optio autem nam totam amet quas quasi, sapiente aliquid accusantium, quo earum dolore distinctio!",
      downloadRecipe:"",
      i1:"consectetur",
      i2:"consectetur",
      i3:"consectetur",
      i4:"consectetur",
      i5:"consectetur",
      src:""
    },
    {
      id: 5,
      foodImage: "imgs/gold-donuts.jpeg",
      foodName: "Rice and Stew", 
      foodtype: "Asian,Golden Doughnut",
      rating: 4.4,
      time: 15,
      pbg: " rgba(145, 126, 1, 0.256)",
      sbg: " rgba(91, 173, 10, 0.256)",
      recipeVideo:"",
      recipeDesc:"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odio sunt sequi natus? Minus eos, eius odit optio autem nam totam amet quas quasi, sapiente aliquid accusantium, quo earum dolore distinctio!",
      downloadRecipe:"",
      i1:"consectetur",
      i2:"consectetur",
      i3:"consectetur",
      i4:"consectetur",
      i5:"consectetur",
      src:""
    }
    
  ];